### ISSUE TITLE
Upgrade from Rails 5.0.1 to Rails 5.0.2

### ISSUE THREAD

**Issue by TrevorJin** [TrevorJin/saintstories#1]

**Comment by roberthdx** [comment]
Upgraded with only minor issues with the previous menu navigation. Replaced the old menu navigation with a side navigation from PureCSS.

**Comment by roberthdx** [comment]
Upgraded. Close #1

**Comment by roberthdx** [comment]
Closes #1

**Comment by roberthdx** [comment]
Closes #1
